version: "3"
services:
  app:
    image: dockerfile
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: dockerfileclient.dev
    ports:
      - "3000:3000"
    volumes:
      - "client/app/node_modules"
      - "./client/:/app"
