# # Version of docker-compose
# version: "3"

# # Containers we are going to run
# services:
#   db:
#     # We use the predefined Postgres image
#     image: postgres:latest
#     environment:
#       # Set user/password for Postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       # Set a path where Postgres should store the data
#       PGDATA: /var/lib/postgresql/data/pgdata2
#     restart: always
#     volumes:
#       - pgdata:/var/lib/postgresql/data2
#   # Our Phoenix container
#   phoenix:
#     # The build parameters for this container.
#     build:
#       # Here we define that it should build from the current directory
#       context: .
#     environment:
#       # Variables to connect to our Postgres server
#       PGUSER: postgres
#       PGPASSWORD: postgres
#       PGDATABASE: lists_dev
#       PGPORT: 5432
#       # Hostname of our Postgres container
#       PGHOST: db
#     ports:
#       # Mapping the port to make the Phoenix app accessible outside of the container
#       - "4000:4000"
#     depends_on:
#       # The db container needs to be started before we start this container
#       - db
# # Define the volumes
# volumes:
#   pgdata:
version: "3"
services:
  app:
    image: dockerfile
    build: .
    ports:
      - "4000:4000"
    # volumes:
    #   - ./src:/app
    depends_on:
      - db
    # command: ["./wait-for-postgres.sh", "db:5432", "echo", "Nani"]
    # environment:
    #   DATABASE_URL: ecto://postgres:postgres@db/lists_dev
    #   HOSTNAME: localhost
    #   PORT: 4000
    # mix phx.gen.secret
    # SECRET_KEY_BASE: g+DmH9ZXkK6YBxrPBW+sOFUpMbDCZwOcwII+kKHio+Pg0Trt9SzRu6b2l5SZX958
    # - SECRET_KEY_BASE
    # - PGHOST: db
    # - PGUSER: postgres
    # - PGPASSWORD: postgres
    # - PGDATABASE: lists_dev
    # - PGPORT: 5432
    env_file:
      - .env
  db:
    image: postgres:10
    # environment:
    #   - POSTGRES_PASSWORD: "postgres"
    #   - POSTGRES_USER: "postgres"
    #   - PGDATA: "/var/lib/postgresql/data"
    #   - PGDATABASE: "lists_dev"
    #   - PGPORT: "5432"
    # restart: always
